apiVersion: apps/v1
kind: Deployment
metadata:
  name: kminion
  labels: &labels
    app: kminion
spec:
  replicas: 1
  selector:
    matchLabels: *labels
  template:
    metadata:
      labels: *labels
    spec:
      containers:
      - name: kminion
        image: docker.io/redpandadata/kminion:v2.2.5@sha256:195cf8ed7b883e8246438a3918c60834c9f285bcd1dcd525e8ea834cb22106c7
        env:
        - name: TELEMETRY_HOST
          value: 0.0.0.0
        - name: TELEMETRY_PORT
          value: "8080"
        - name: EXPORTER_IGNORE_SYSTEM_TOPICS
          value: "true"
        - name: EXPORTER_NAMESPACE
          value: kminion
        - name: LOG_LEVEL
          value: info
        - name: KAFKA_BROKERS
          value: bootstrap:9092
        - name: KAFKA_CONSUMER_OFFSETS_TOPIC_NAME
          value: __consumer_offsets
        ports:
        - name: metrics
          containerPort: 8080
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 10
